# POST http://127.0.0.1:9000/auth/signup
# Content-Type: application/json

# {
#   "id": "test2@example.com",
#   "nickname": "테스터2",
#   "password": "qwer"
# }

# POST http://127.0.0.1:9000/auth/signin
# Content-Type: application/json

# {
#   "id": "test2@example.com",
#   "password": "qwer"
# }

# GET http://127.0.0.1:9000/auth/user
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VyX25hbWUiOiLthYzsiqTthLAxIiwiaWF0IjoxNjY3NTIxMzA0LCJleHAiOjE2Njc2MDc3MDR9.4L8i7A1xnt7RaoEqj4aPJV6yQjUBoeDDaeQYR9MZRhU

# POST http://127.0.0.1:9000/workspace
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VyX25hbWUiOiLthYzsiqTthLAxIiwiaWF0IjoxNjY3NTIxMzA0LCJleHAiOjE2Njc2MDc3MDR9.4L8i7A1xnt7RaoEqj4aPJV6yQjUBoeDDaeQYR9MZRhU

# {
#   "name": "워크스페이스1",
#   "users": ["test2@example.com", "test3@example.com"]
# }

# POST http://127.0.0.1:9000/channel
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdDFAZXhhbXBsZS5jb20iLCJ1c2VyX25hbWUiOiLthYzsiqTthLAxIiwiaWF0IjoxNjY3NTIxMzA0LCJleHAiOjE2Njc2MDc3MDR9.4L8i7A1xnt7RaoEqj4aPJV6yQjUBoeDDaeQYR9MZRhU

# {
#   "name": "테스트 채널1",
#   "workspace_id": "pPnOtC7EXQPSTMHq",
#   "users": ["test2@example.com"]
# }